### ISSUE TITLE
Cron support

### ISSUE THREAD

**Issue by olafc** [jchaney/owncloud#1]
Hey Josh,

first of all, awesome owncloud docker image! Just one thing that would make the image perfect: cron support. This would speed up site access significantly.

http://doc.owncloud.org/server/7.0/admin_manual/configuration/background_jobs.html#cron

To have proper cron support, I would also recommend using a dockerized ubuntu base image:
 https://registry.hub.docker.com/u/phusion/baseimage/

I could implement and test such a change, would you accept pull requests?

Best regards,

Olaf

**Comment by silvio** [comment]
hi,

I need this feature too. So I have implemented it in https://github.com/silvio/docker-owncloud/tree/sfr/cron and have done a pull request https://github.com/jchaney/owncloud/pull/7

**Comment by jchaney** [comment]
I'm all for cron support, but not going to change the base image to phusion (in regards to Olaf's comment). Not a fan of that Docker philosophy.

**Comment by silvio** [comment]
me too. I don't changed the base image for this little thing.

**Comment by silvio** [comment]
Its included since january.
