### ISSUE TITLE
Switch to Debian jessie base image?

### ISSUE THREAD

**Issue by ypid** [jchaney/owncloud#13]
Debian is the recommended base image for Docker. See https://docs.docker.com/articles/dockerfile_best-practices/#from

Any thoughts?

**Comment by ypid** [comment]
I am testing it on Debian Jessie. The only changes required so far were the packages bzip2 and cron which need to be added.

**Comment by silvio** [comment]
I will test debian:jessie too. Can you create a pull request and let test the users than?
