### ISSUE TITLE
always_populate_raw_post_data should be set to -1 in php.ini

### ISSUE THREAD

**Issue by hourliert** [jchaney/owncloud#19]
Hi,

First, thank for this good docker image. It is very useful! 
I get a warning in my admin panel and in /var/log/cron/owncloud.log :

```
PHP is configured to populate raw post data. Since PHP 5.6 this will lead to PHP throwing notices for perfectly valid code.
To fix this issue set <code>always_populate_raw_post_data</code> to <code>-1</code> in your php.ini
```

If I do what it is asked, the warning disappear. Could you fix that in the image ?

Thanks in advance.

**Comment by silvio** [comment]
yes, indeed - I will change this.

**Comment by silvio** [comment]
Currently I test #20 on my own server...

**Comment by silvio** [comment]
tested and looks okay.
