### ISSUE TITLE
Nessesary to disable and enable apps after upgrade of containers to use apps

### ISSUE THREAD

**Issue by ypid** [jchaney/owncloud#22]
See https://github.com/jchaney/owncloud/pull/10#issuecomment-76670596

**Comment by ypid** [comment]
I found a solution to this. Refer to the [documentation](https://doc.owncloud.org/server/8.0/admin_manual/installation/apps_management_installation.html#using-custom-app-directories).

One has to add this piece to the config.php:

    "apps_paths" => array (
      0 => array (
        "path"     => OC::$SERVERROOT."/apps",
        "url"      => "/apps",
        "writable" => false,
      ),
      1 => array (
        "path"     => OC::$SERVERROOT."/apps_persistent",
        "url"      => "/apps_persistent",
        "writable" => true,
      ),
    ),

and then put `/var/www/owncloud/apps_persistent` on persistent storage.

**Comment by silvio** [comment]
ah - this is good. thx - I have to look how I could integrate this.
