### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ypid** [jchaney/owncloud#28]
@jchaney @silvio 
I would like to put this project under a FOSS license specifically AGPLv3
http://www.gnu.org/licenses/agpl-3.0.de.html
What do you think?

**Comment by silvio** [comment]
@ypid I'm out from this project.

**Comment by ypid** [comment]
No problem. I am [maintaining it](https://github.com/jchaney/owncloud/pull/10#issuecomment-128501857). The question is just if you agree because this project is not yet licensed …

**Comment by silvio** [comment]
Take a gpl compatible license. A good overview of licences you can get here: <http://www.gnu.org/licenses/license-list.html>.

**Comment by jchaney** [comment]
I'm good with AGPLv3

**Comment by ypid** [comment]
All right. AGPLv3 it is. Thanks.
