### ISSUE TITLE
Store the data outside the container

### ISSUE THREAD

**Issue by taxilian** [jchaney/owncloud#30]
I love what you've done here, and would like to use the image, but I don't see any easy way to store the data outside of the container or anything designating a volume inside the container which would cause the data to persist; this seems to mean that you can't ever upgrade the container.

Am I missing something?

**Comment by ypid** [comment]
Check the [Makefile](https://github.com/jchaney/owncloud/blob/master/Makefile#L39-Lundefined) for an example. I am using bind mounting with Docker in my environments as I don’t quite trust the volume Docker thing. Also doing backups are easier that way and I am more flexible when other ownCloud images store/have there ownCloud data directory in a different location.

Nice that you like it :smile:

**Comment by ingwinlu** [comment]
is there a reason why you don't store the owncloud config outside as well (i.e. ` -v /docker/owncloud/config:/owncloud`)?

**Comment by ypid** [comment]
The reason why the `config.php` is not stored outside by default is that I think that it is not generally needed. I have the `config.php` outside of my ownCloud containers but with the current state of this image it should not be needed anymore. You still do it of course. This is how I usually do this:

1. `docker run ...` for the first time.
2. `docker exec $name cat /owncloud/config.php > /new/target/on/the/host/config.php`
3. `docker run --volume /srv/staging/owncloud/config.php:/owncloud/config.php ...`

Is it something common that you want to change in the config file?

PS: Thanks, you are welcome.

**Comment by ingwinlu** [comment]
I actually am not sure what the implications of it not being outside are, but I suspect that it would require a new database setup every time as the password hash and the other configuration data is in the config.php.

That is also the reason I want it outside, to keep it persistent across container removal. I like my containers that way, making for easy systemd organized containers that are also easy to upgrade.

**Comment by ypid** [comment]
Thnaks @ingwinlu. I have missed that. Fixed.

**Comment by ypid** [comment]
The issue should fixed now. Feel free to reopen/comment if there are still problems.
