### ISSUE TITLE
Image for ARM machines

### ISSUE THREAD

**Issue by joeplus** [jchaney/owncloud#31]
Hi and thanks for the great work!

My question is, if the docker image also works on arm based systems and if not what would need to change to do so?

Thanks and best regards
Jörg

**Comment by ingwinlu** [comment]
it would need a arm base image

**Comment by joeplus** [comment]
That was my assumption as well. What about the other required packages. Are there any where not arm version exists?

**Comment by ypid** [comment]
I guess this can be done. I have this ownCloud image running on i368 using a self build base image.
See https://github.com/docker-32bit/debian/issues/4.
mkimage.sh usually auto detects the host architecture so you just need to build the base image and this image your self and it should work.

**Comment by na-g** [comment]
@joeplus While I haven't attempted a non-SQLite deployment, changing the FROM to ```FROM resin/rpi-raspbian:jessie``` is all that is needed to build the container. Note that [resin/rpi-raspbian](https://hub.docker.com/r/resin/rpi-raspbian/) is not an official rasbian container. See: [rpi-rasbian source](https://bitbucket.org/rulemotion/resin-rpi-raspbian). You can look at the top of the Dockerfile in my [rpi fork](https://github.com/na-g/rpi-owncloud) of this repo if any of that didn't make sense.

**Comment by ypid** [comment]
I assume that it is doable and closing this issue now after a few years have passed. Ref: #62.
