### ISSUE TITLE
owncloud docker starts then stops

### ISSUE THREAD

**Issue by zaralger** [jchaney/owncloud#32]
Hi, 
I'm trying to use your docker by pulling it directly from github, but after a `make owncloud-production`, the docker seems to start, then disappears from `docker ps`.

Did I miss something ? 

Thanks !

**Comment by ypid** [comment]
Can you show me the output of `docker logs owncloud-production` and `docker logs owncloud-mariadb`? Also, it might be easier to start testing with `make owncloud`.

**Comment by zaralger** [comment]
Thanks for answering that quick, here are the logs, sorry I've should have post it before:

`docker logs owncloud-production` 

> $ docker logs owncloud-production
> Copying nginx.conf with SSL support …
> Starting server … 
> tail: warning: --retry only effective for the initial open
> ==> /var/log/nginx/access.log <==
> 
> ==> /var/log/nginx/error.log <==
> 
> ==> /var/log/cron/owncloud.log <==


`docker logs owncloud-mariadb`

> $ docker logs owncloud-mariadb 
> 151019 12:20:58 [Note] mysqld (mysqld 10.0.21-MariaDB-1~jessie) starting as process 1 ...
> 151019 12:20:58 [Note] InnoDB: Using mutexes to ref count buffer pool pages
> 151019 12:20:58 [Note] InnoDB: The InnoDB memory heap is disabled
> 151019 12:20:58 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 151019 12:20:58 [Note] InnoDB: Memory barrier is not used
> 151019 12:20:58 [Note] InnoDB: Compressed tables use zlib 1.2.8
> 151019 12:20:58 [Note] InnoDB: Using Linux native AIO
> 151019 12:20:58 [Note] InnoDB: Not using CPU crc32 instructions
> 151019 12:20:58 [Note] InnoDB: Initializing buffer pool, size = 256.0M
> 151019 12:20:58 [Note] InnoDB: Completed initialization of buffer pool
> 151019 12:20:58 [Note] InnoDB: Highest supported file format is Barracuda.
> 151019 12:20:58 [Note] InnoDB: The log sequence numbers 1616767 and 1616767 in ibdata files > do not match the log sequence number 1616787 in the ib_logfiles!
> 151019 12:20:58 [Note] InnoDB: Database was not shutdown normally!
> 151019 12:20:58 [Note] InnoDB: Starting crash recovery.
> 151019 12:20:58 [Note] InnoDB: Reading tablespace information from the .ibd files...
> 151019 12:20:58 [Note] InnoDB: Restoring possible half-written data pages 
> 151019 12:20:58 [Note] InnoDB: from the doublewrite buffer...
> 151019 12:20:59 [Note] InnoDB: 128 rollback segment(s) are active.
> 151019 12:20:59 [Note] InnoDB: Waiting for purge to start
> 151019 12:20:59 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.25-73.1 started; > > log sequence number 1616787
> 151019 12:20:59 [Note] Plugin 'FEEDBACK' is disabled.
> 151019 12:20:59 [Note] Server socket created on IP: '::'.
> 151019 12:20:59 [Warning] 'proxies_priv' entry '@% root@a89c7709c18e' ignored in --skip-v name-resolve mode.
> 151019 12:20:59 [Note] Event Scheduler: Loaded 0 events
> 151019 12:20:59 [Note] mysqld: ready for connections.
> Version: '10.0.21-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

**Comment by ypid** [comment]
Looks normal to me. And the `owncloud-production` container exits right away?

**Comment by ypid** [comment]
You read the `Makefile`? For running in production you need to make sure that `/etc/ssl/certs/ssl-cert-snakeoil.pem` and so on exists … I will update the docs.

**Comment by zaralger** [comment]
I didn't pay attention to the SSL lines in the makefile, it seems I was wrong...
thanks for answering !

**Comment by ypid** [comment]
Issue should be fixed. Feel free to comment/reopen for further questions.
