### ISSUE TITLE
Don’t allow ownCloud update via the web interface.

### ISSUE THREAD

**Issue by ypid** [jchaney/owncloud#37]
To avoid the case where a user with admin permissions in ownCloud updates the container and on next redeployment of the container the instance might be downgraded. The [official docker image for ownCloud](https://hub.docker.com/_/owncloud/) solves this problem by making the ownCloud setup president. This will not be done for this image.

Example warning: 'Downgrading is not supported and is likely to cause unpredictable issues (from 8.2.1.4 to 8.1.4.2)'

**Comment by hadim** [comment]
So Owncloud update will be possible only via something like `docker stop && docker rm && docker build && docker start`.

**Comment by ypid** [comment]
I would prefer that because of the downgrade problematic.

**Comment by hadim** [comment]
That make sense to me. It shoud be documented on the README I guess.
