### ISSUE TITLE
DB_ENV_MYSQL_HOST?

### ISSUE THREAD

**Issue by dvwiz** [jchaney/owncloud#40]
Since docker is phasing out --link in favor of docker network, is there an environmental variable for telling the owncloud container the address of my existing mysql container? For example, the official wordpress container has a WORDPRESS_DB_HOST variable.

**Comment by ypid** [comment]
The DB host is configured in the `config.php` of ownCloud on first setup. Changing that later via environment variables would be an idea. Consider sending a PR if you need it.

**Comment by dvwiz** [comment]
Ah, cool. Setting it up within the ownCloud setup will work just fine. Thanks for the quick response.
