### ISSUE TITLE
Add strong diffie-hellman prime

### ISSUE THREAD

**Issue by FreekKalter** [jchaney/owncloud#42]
I was curious how ssllabs would rate my brand new owncloud server. So I
tested it and initially got a B rating. The best improvement was to add a stronger (4096 bit) prime for diffie-hellman keyexchange. 
So after a couple of small changes, i got it running and have a [A+ rating](https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.kalteronline.org&hideResults=on) now.
You can see what i did [here](https://github.com/FreekKalter/owncloud/commit/3b0e91ba9c4fb981e4f058569b90d3d5045ed6ec), 3 lines basically.
It takes a while to build the image now, since I am generating the prime (which takes forever) in the Dockerfile. 
So it is probably better to add a precalculated prime like [rfc3526](http://tools.ietf.org/html/rfc3526#section-5).

This might be something to discuss.

**Comment by ypid** [comment]
Thanks very much for testing this :+1: I am not sure if generating the DH parms in the image is the best idea. Ideally the Docker container would regularly regenerate DH params like it is done in the DebOps project in [`debops.dhparam`](https://github.com/debops/ansible-dhparam). Regularly regenerating in this context would practically mean on each restart/redeployment if lets the DH params are older than 7 days. Because Docker containers need to be redeployed on a regular basis/automated anyway. DH params would then be saved on persistent storage. You are welcome to create a PR for this.

**Comment by FreekKalter** [comment]
Yes i agree, that generating it in the container would be a better
solution. I dont think it is necessary to keep regenerating it though.
Because some sources even suggest It is better to choose a prime which is
known to work and stick with that. (see [rfc3526](
http://tools.ietf.org/html/rfc3526#section-5) But I Will look in tot that
tonight. Keep you posted.

Op maandag 8 februari 2016 heeft Robin Schneider <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> het volgende
geschreven:

**Comment by FreekKalter** [comment]
Oké, so after some research here is what is in my opinion the best solution.  
First of all, regenerating the DH params really is not necessary, especially after 7 days. I haven't found anything like this being best practice. Especially with a 4096 bit prime.

So that leaves 2 options:
1) Going with a prime that is precalculated, one from [rfc3526](http://tools.ietf.org/html/rfc3526#section-5) for example. Whit a prime like this the algorithm can use g=2 as generator, which has some (little) computational advantage. The disadvantage is that if many people are using it, you come at risk when it does happen to have a weakness.

2) Generating a 4096 bit prime the first time the container starts , and saving it to permanent storage. The advantage is that is that not a whole lot of other people are using the same prime, solving the disadvantage of point 1. The price you pay for it is on first time running the container, because it can take a while to calculate.

I choose option 2. This is what most people seem to be doing, and what most ssl configuring guides and stackexchange answers point to. And because it takes away the fear of an attack like logjam, where a part of the impact came from the fact that lots of sites where using the same primes.

**Comment by ypid** [comment]
That is a reasonable decision. Thanks very much. :+1: I agree that this is already a lot better than using the default params. And if someone really wants to regenerate the params on each restart, they can easily do this by deleting the file on reboot. I will test your PR #43 a bit and merge it probably tomorrow.

**Comment by ypid** [comment]
Merged. Thanks :+1:
