### ISSUE TITLE
what about if I use CoreOs?? 

### ISSUE THREAD

**Issue by jujes** [jchaney/owncloud#48]
Hi, I'm new using CoreOs and don't know how user **make**...
**Some idea? **
Thanks in advance,

**Comment by ypid** [comment]
Not sure about CoreOS as I have not yet used it. You don’t really need `make` to get the basics, you can check [GNU make docs](https://www.gnu.org/software/make/). Example target: https://github.com/jchaney/owncloud/blob/6454579d9a0362e367abc1c10877609316c18660/Makefile#L57
