### ISSUE TITLE
problem with connecting to mariadb base

### ISSUE THREAD

**Issue by paulz1** [jchaney/owncloud#57]
At first thank you very much for your job. 

Nevertheless :-) I have some problem to get it work. Probably I did something wrong, but I could not found what.
1) I successfully built docker image using "make build"
2) then I started owncloud-production (make owncloud-production)
3) the both containers (mariadb and owncloud-production started successfully)
$ docker ps
1c0b09191e8c        jchaney/owncloud    "bootstrap.sh"           About an hour ago   Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   owncloud-production
584bd684e7da        mariadb             "docker-entrypoint.sh"   About an hour ago   Up About an hour    3306/tcp                                   owncloud-mariadb

And I could connect to owncloud web-interface 
4) I got mariadb password using : make owncloud-mariadb-get-pw

5) but when I try to use it to configure database for owncloud (using web-interface), I got the problem with database

Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud-production'@'172.17.0.5' (using password: YES)

6) As additional steps.
make owncloud-mariadb-cli - does not work neither;

If I try to go to mariadb container and try to connect to database locally, it does not work.

$ docker exec -it owncloud-mariadb /bin/bash
root@584bd684e7da:/# mysql -h localhost -uowncloud-production -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'owncloud-production'@'localhost' (using password: YES)

So... could you give a clue where to search the solution?
May be there is something that I don't understand about pwgen and how to get mariadb password?

Thank you very much in advance.

Thanks,
Paul Zakharov

**Comment by fenollp** [comment]
Have you considered using docker compose? https://github.com/jchaney/owncloud/#docker-compose-support

**Comment by ypid** [comment]
@paulz1 Hm, not sure what the problem might be in this case. Is it reproducible? What happens when you remove the containers and recreate them?

**Comment by paulz1** [comment]
Ok, you could close it.
It was my fault. I completly forgot that I had already some other containers with db as name.
So 
--link owncloud-mariadb:db
in owncloud-production give some strange effects.
I change it to --link owncloud-mariadb:db_own and now it works.

By the way after solving this problem I had the same problem as in issue https://github.com/jchaney/owncloud/issues/46
that I solved without understanding  why it did not work before and why it works now. I'll write a little comment in #46 discussion topic.
