### ISSUE TITLE
how recover maridb root password ?

### ISSUE THREAD

**Issue by paulz1** [jchaney/owncloud#60]
Is it possible to recover MariaDB root password?

I launch recently an owncloud instance using your docker.
At this moment I noted only password for mysql user owncloud-production. I did not note the password for root.

After that I stopped and relaunch my owncloud. Upgrade the image (docker pull jchaney/owncloud) as well. Etc.

And now I find that I don't know the root password for mariadb.

`make owncloud-mariadb-get-pw`

does not show the correct information. Probably because each time when I launch 
`make owncloud-production`
these passwords are generated randomly (shell pwgen --secure 40 1).

The procedure to recover root password for mysql/mariadb does not work as well, because in owncloud-mariadb container mysqld process have a PID 1, so I could not stop or kill it.

Even if it (owncloud docker) works well without knowing mariadb root password, it seems to me that it preferable to have this password to get access to the database in case of some troubles.

So is there some methods to recover root password in this situation?

**Comment by ypid** [comment]
Fixed:

```
make owncloud-mariadb-get-pw
docker exec owncloud-mariadb \
        sh -c 'env | egrep "^MYSQL_" | sed "s/=/: /"; \
                echo "Database host: db"'
MYSQL_ROOT_PASSWORD: password
MYSQL_PASSWORD: password
MYSQL_USER: owncloud-production
MYSQL_DATABASE: owncloud-production
Database host: db
```

But the interesting question is why http://dbversity.com/how-to-reset-a-root-password-in-mariadb-on-linux/ did not work. I tried it but could not login as  `debian-sys-main`. Probably some setting. Anyway.

**Comment by paulz1** [comment]
Oh, sorry. 
Yes I could use `make owncloud-mariadb-get-pw` or even `docker exec owncloud-mariadb env`
But it does not work.
It gives me a password that was generated by using `shell pwgen --secure 40 1` and not the original password.

As I understand the situation.
First time when I run owncloud-production, mariadb database was created, and the  passwords for root and owncloud-production users were set.

Now, each time when I launch `make owncloud-production`, the new password a generated but it does not take effect because I use some persistent storage for my databse and this is a quota from mariadb docker manual :

> If you start your mariadb container instance with a data directory that already contains a database (specifically, a mysql subdirectory), the $MYSQL_ROOT_PASSWORD variable should be omitted from the run command line; it will in any case be ignored, and the pre-existing database will not be changed in any way.

But the owncloud-mariadb-get-pw command shows the env variables that correspond to `shell pwgen --secure 40 1`


So this is the output from my server.
But the MYSQL_ROOT_PASSWORD is wrong. It does not work.
And MYSQL_PASSWORD is wrong too (and I know it, because I noted the correct one, and I could still connect to database using it).
```
~/Docker/owncloud$ make owncloud-mariadb-get-pw
docker exec owncloud-mariadb \
	sh -c '(env | egrep "^MYSQL_"; \
			env | egrep "^MYSQL_(DATABASE|PASSWORD)="; \
		) | sed "s/=/: /"; \
		echo "Database host: db_own"'
MYSQL_ROOT_PASSWORD: swgRTA0bq8nr0rWsFYNxpIStPpvIdBVGsAy1ZQjC
MYSQL_PASSWORD: jjor0vTGBs3SW6xS0WAHnypqm6ROtVHP9rAV4kFr
MYSQL_USER: owncloud-production
MYSQL_DATABASE: owncloud-production
MYSQL_PASSWORD: jjor0vTGBs3SW6xS0WAHnypqm6ROtVHP9rAV4kFr
MYSQL_DATABASE: owncloud-production
Database host: db_own
```

**Comment by paulz1** [comment]
> But the interesting question is why http://dbversity.com/how-to-reset-a-root-password-in-mariadb-on-linux/ did not work. I tried it but could not login as debian-sys-main. Probably some setting. Anyway.

By the way, yes I confirm. I tried this method as well and it does not work. I don't find out why.

**Comment by ypid** [comment]
Ah, right, sorry. You are correct. I knew I missed something. Hm, In that case [automysqlbackup](https://packages.debian.org/search?keywords=automysqlbackup) could be used to get a db dump, then you could remove the db container and persistent storage and recreate the owncloud db with the dump. I guess a note to the readme should be added about the root pw. Does this work for you?

**Comment by paulz1** [comment]
Ok, thank you for suggestion. I'll try it tomorrow.

Just to be sure about steps to do:
1) create a backup/dump of database;
2) remove mariadb container and the persistent database store;
3) recreate new mariadb container (save the password to root and owncloud-production user)
4) restore backup to new database...
Am I right?

Does owncloud will automatically recover all of settings after this?

**Comment by ypid** [comment]
Looks good.

It should, yes. The ownCloud container and file data can be left as is and only the ownCloud DB can be restored.

**Comment by paulz1** [comment]
Ok, thanks.
Your note about MariaDB root password seems very clear and useful.
With the previous commit (add mariadb root password to get-password) it will probably avoid all sort of these problems.

**Comment by ypid** [comment]
I hope so and sorry for the inconvenience and thanks for reporting!

**Comment by paulz1** [comment]
Hmmm...
Now the problem seems to be in fact that `automysqlbackup` does not work.
I got 

> ERROR 1045 (28000): Access denied for user 'debian-sys-maint'@'localhost' (using password: YES)

when I try to install the package.
It explains as well why login as debian-sys-main does not work.
There are some articles about `Access denied for user 'debian-sys-maint'@'localhost'`, but the solution is to connect as root and then do
`GRANT ALL PRIVILEGES ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '<password>';`

but I could not do...
For now, I will try to do backup as owncloud-production user.

**Comment by ypid** [comment]
All right, I gave it a try again and was able to reset the MariaDB root password:

1. Temoprarly update the makefile:

```Makefile
owncloud-mariadb:
	-@docker rm --force "$@"
	docker run \
		--name "$@" \
		$(DOCKER_RUN_OPTIONS) \
		--volume $(docker_owncloud_permanent_storage)/db:/var/lib/mysql \
		--env "MYSQL_ROOT_PASSWORD=$(shell pwgen --secure 40 1)" \
		--env "MYSQL_USER=$(docker_owncloud_mariadb_user)" \
		--env "MYSQL_DATABASE=$(docker_owncloud_mariadb_user)" \
		--env "MYSQL_PASSWORD=$(shell pwgen --secure 40 1)" \
		$(image_mariadb) --skip-grant-tables
```

2. Run `make owncloud-mariadb`
3. In a second shell, run `docker exec -ti owncloud-mariadb mysql -uroot` which should drop you right into a MariaDB root shell :wink:
4. Reset root password following https://support.rackspace.com/how-to/mysql-resetting-a-lost-mysql-root-password/

Hope this helps.

**Comment by paulz1** [comment]
Sorry I was a little busy yesterday.
I try this solution now and it works like a charm.

Thank you very much for assistance.
