### ISSUE TITLE
tags and comments

### ISSUE THREAD

**Issue by paulz1** [jchaney/owncloud#61]
I'm not sure this a real issue. May be it's some problem with installation.
But actually Comments and Tags features don't work.

The Tag feature is not available at all (there is no field to add tag).

The Comment field is available. But when I add comment it gives some error ("[object Object]"). And the comment is not stored (or not added).

Using `docker logs owncloud-production`
I could see some error associated with this event : 
```
==> /var/log/nginx/error.log <==
2017/03/01 18:10:22 [error] 121#0: *432 upstream sent invalid status "0" while reading response header from upstream, client: ::xxxx, server: , request: "POST /remote.php/dav/comments/files/672055/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxx"
```
(I put some xxx in the addresses, just because of little paranoia)

Although it's a some minor issue, just interesting why it happens. And is it easy to repair?

**Comment by ypid** [comment]
I just tested this with a blank container created using `make owncloud-dev` and it all worked for me. The tags might be a bit hidden. Look above the Activites, Comments, Sharing, Version tabs. There is should be the field where you can enter tags.

But the error log you posted. Would need to be investigated.

> (I put some xxx in the addresses, just because of little paranoia)

I encourage you to do that :wink:

**Comment by paulz1** [comment]
Ok, it was also my idea to test it by creating a new-one blank container.
So if it works for you it's probably some problem with my install.
But by the way it gives me another little question.

If I want to play (to change) with nginx.conf.
I won't to build my own image, because you do a great job and it's easy to me to use directly your image.
But you do an ADD of nginx.conf in Dockerfile, so I do rebuild an image if I want to change something.

At the moment I do the trick by adding this line to Makefile owncloud-production task :
`--volume "~/owncloud/local_configs/nginx_ssl.conf:/root/nginx_ssl.conf"`

It seems that it works. But I ask myself if it's a good way to do it?

This question sounds a little bit irrelevant with the original issue. But may be not so irrelevant, as at first I thought that may be the problem of comments and tag could be explained by some nginx settings.

**Comment by ypid** [comment]
> `--volume "~/owncloud/local_configs/nginx_ssl.conf:/root/nginx_ssl.conf"`

I do similar things and I don’t see a problem with that. You could also build an image ontop of this one but just for playing with nginx config I don’t think that is necessary plus it takes longer to test a new nginx config.

> I won't to build my own image, because you do a great job

Thanks for the compliment (which also goes to all previous maintainers) but the Docker image is not actively developed. I just try my best to support it.

**Comment by paulz1** [comment]
Some additional info about tag problem.
When I try to add a comment, I see using Firebug plugin that there is a POST sent :

POST https://my_owncloud/remote.php/dav/comments/files/756700/
And in the json there is an information about comment.

But I get "`NetworkError: 502 Bad Gateway`" from nginx...
Now... I don't understand nothing... why nginx could reply Bad Gateway...

**Comment by ypid** [comment]
Hm, this image might need some work. Can you try with https://github.com/owncloud/documentation/blob/master/admin_manual/installation/nginx_examples.rst (might need some work)? For reference, I am currently more involved in [debops.owncloud](https://github.com/debops/ansible-owncloud).

**Comment by paulz1** [comment]
Still looking around this problem...
 I see a lot of messages in owncloud.log about :

> "app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead.

Wondering if it's something important?
always_populate_raw_post_data seems to be already -1 in php.ini

**Comment by ypid** [comment]
You might want to try with the nginx example I posted above and see if the problems go away. This docker images does not currently follow the latest community suggestions about nginx.

**Comment by paulz1** [comment]
Sorry, ypid, I took a little break before reply.
Finally I re-did my installation from zero. And now the tags and comments work well without any problem.
So it was certainly some things that I touched during the first try (for example the first try was done on a temporary server and after that we changed temporary server's hostname (for example test.domain.com) to good one (for example good.domain.com)... it seems that it was not a good idea, because I saw some residues of test.domain.com in conf files and in the database. I tried to correct them, but may be I did not see all of occurrence. May be it was a source of problem, or some others things).

It does not matter, because I redid the new, clear installation and now it works perfectly.
Thanks for you link about nginx's conf. Even if the problem go away, it's still interesting to read this page.
The problem is that there are a lot of things on this page and it's not evident which are good for us, and which are not... But nevertheless, it's still interesting.

I will have a look as well on debops.owncloud project. 
Thanks for your help.

P.S.: I don't know... but probably you could close issue?

**Comment by ypid** [comment]
Thanks for the feedback. I am glad that I was able to help. Yes, I am going to close the issue then now that it works for you.
